package org.apache.shardingsphere.example.core.api;

/**
 * @author wanghaitao
 * @date 2019/12/31 16:09
 */
public enum SceneType {
    SHARDING_ONLY,
    SHARDING_ENCRYPT,
    SHARDING_MASTER_SLAVE,
    SHARDING_MASTER_SLAVE_ENCRYPT,
    ENCRYPT_ONLY,
    MASTER_SLAVE_ONLY,
    ORCHESTRATION_SHARDING_ONLY,
    ORCHESTRATION_SHARDING_ENCRYPT,
    ORCHESTRATION_SHARDING_MASTER_SLAVE,
    ORCHESTRATION_SHARDING_MASTER_SLAVE_ENCRYPT,
    ORCHESTRATION_ENCRYPT_ONLY,
    ORCHESTRATION_MASTER_SLAVE_ONLY
}
